language: node_js
matrix:
  include:
    - node_js: "node"
      env: CI=coverage
    - node_js: "8"
    - node_js: "10"


before_install:
  - if [ "$NODE_V" = "4" ]; then npm i -D eslint@4.19.1 espree@3.5.4; fi
  - if [ "$NODE_V" = "4" ]; then npm uninstall -D @mysticatea/eslint-plugin eslint-plugin-es; fi
deploy:
  skip_cleanup: true
  provider: npm
  email: $EMAIL
  api_key: $NPM_TOKEN
  on:
    tags: true
notifications:
  email: false
after_success:
  - if [ "$CI" = "coverage" ]; then npm install coveralls --no-save && cat ./coverage/lcov.info | ./node_modules/.bin/coveralls; fi
